BUILD_CPU="bcmrpi"
BUILD_CPU_ARCH="arm"
BUILD_CPU_FAMILY="v6l"

BOARD_CPU="bcmrpi"
BOARD_CPU_ARCH="arm"
BOARD_CPU_FAMILY="v6l"

BOARD_LOADER=""

BOARD_KERNEL="${BOARD_CPU}"
BOARD_KERNEL_CONFIG="default"
BOARD_KERNEL_LOADER="u-boot-sunxi"

BOARD_ROOTFS="${BOARD_CPU_ARCH}${BOARD_CPU_FAMILY}"
BOARD_ROOTFS_FAMILY="raspbian"
BOARD_ROOTFS_VERSION="stable"

# Include the default values last.
source ${ARMSTRAP_BOARDS}/.defaults/bcmrpi.sh
