BOARD_CONFIG="${ARMSTRAP_CONFIG,,}"

if [ -z "${ARMSTRAP_LANG}" ]; then
  BOARD_LANG="${LANG}"
else
  BOARD_LANG="${ARMSTRAP_LANG}"
fi

if [ -z "${ARMSTRAP_LANGUAGE}" ]; then
  BOARD_LANGUAGE="${LANGUAGE}"
else
  BOARD_LANGUAGE="${ARMSTRAP_LANGUAGE}"
fi

BOARD_LANG_EXTRA="${ARMSTRAP_LANG_EXTRA}"
 
if [ -z "${ARMSTRAP_TIMEZONE}" ]; then
  BOARD_TIMEZONE="America/Montreal"
else
  BOARD_TIMEZONE="${ARMSTRAP_TIMEZONE}"
fi

if [ ! -z "${ARMSTRAP_ROOTFS_FAMILLY}" ]; then
  BOARD_ROOTFS_FAMILLY="${ARMSTRAP_ROOTFS_FAMILLY}"
fi

if [ ! -z "${ARMSTRAP_ROOTFS_VERSION}" ]; then
  BOARD_ROOTFS_VERSION="${ARMSTRAP_ROOTFS_VERSION}"
fi

if [ ! -z "${ARMSTRAP_KERNEL_CONFIG}" ]; then
  BOARD_KERNEL_CONFIG="${ARMSTRAP_KERNEL_CONFIG}"
fi

if [ ! -z "${ARMSTRAP_KERNEL_VERSION}" ]; then
  BOARD_KERNEL_VERSION="${ARMSTRAP_KERNEL_VERSION}"
fi

BOARD_ROOTFS_PACKAGE="${BOARD_ROOTFS}-${BOARD_ROOTFS_FAMILLY}-${BOARD_ROOTFS_VERSION}.txz"
BOARD_ROOTFS_RECONFIG="${ARMSTRAP_DPKG_RECONFIG}"

# Not all packages can be install this way.
BOARD_DPKG_EXTRAPACKAGES="${BOARD_DPKG_EXTRAPACKAGES} ${ARMSTRAP_DEBIAN_EXTRAPACKAGES}"
  
# Theses are packages included with or generated by the script. The script will automatically include .deb files in the dpkg directory
BOARD_DPKG_LOCALPACKAGES=""
  
BOARD_SERIAL_ID="T0"
BOARD_SERIAL_RUNLEVEL="2345"
BOARD_SERIAL_TERM="ttyS0"
BOARD_SERIAL_SPEED="115200"
BOARD_SERIAL_TYPE="vt100"

BOARD_FSTAB=("/dev/root:/:ext4:defaults:0:1")

if [ -z ${ARMSTRAP_LOADER_ROOT} ]; then
  BOARD_LOADER_ROOT="/dev/mmcblk0p1"
else
  BOARD_LOADER_ROOT="${ARMSTRAP_LOADER_ROOT}"
fi

BOARD_MAC_PREFIX=0x000246
  
BOARD_LOADER_CMD="${ARMSTRAP_MNT}/boot/boot.cmd"
BOARD_LOADER_SCR="${ARMSTRAP_MNT}/boot/boot.scr"
BOARD_LOADER_UENV="${ARMSTRAP_MNT}/boot/uEnv.txt"
BOARD_LOADER_FEX="/boot/${BOARD_CONFIG}.fex"
BOARD_LOADER_BIN="/boot/script.bin"
BOARD_LOADER_UBOOT=("${ARMSTRAP_MNT}/boot/u-boot-sunxi-with-spl.bin:1024:8")
BOARD_LOADER_CMDLINE="console=tty0 console=${BOARD_SERIAL_TERM},${BOARD_SERIAL_SPEED} hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x720p60 root=${BOARD_LOADER_ROOT} rootwait panic=10"
#
# Theses are defaults values that can be overwritten by uEnv.txt
#
BOARD_LOADER_BOOTCMD=("root=${BOARD_LOADER_ROOT} rootwait")
BOARD_LOADER_BOOTUENV=("bootargs=${BOARD_LOADER_CMDLINE}")

BOARD_DISK_LAYOUT=("1:/:ext4:-1")

#############################################################################
#
# Host configuration
#
# Add any prerequisition the board need to be build. 
BOARD_PREREQ="u-boot-tools qemu qemu-user-static parted kpartx lvm2 binfmt-support libusb-1.0-0-dev dosfstools libncurses5-dev"
