
if [ ! -z "${ARMSTRAP_BOARD_KERNEL}" ]; then
  BOARD_KERNEL="${ARMSTRAP_BOARD_KERNEL}"
fi

if [ ! -z "${ARMSTRAP_BOARD_LOADER}" ]; then
  BOARD_LOADER="${ARMSTRAP_BOARD_LOADER}"
fi

if [ ! -z ${ARMSTRAP_UIMAGE_LOAD_ADDRESS} ]; then
  BOARD_UIMAGE_LOAD_ADDRESS="${ARMSTRAP_UIMAGE_LOAD_ADDRESS}"
else
  BOARD_UIMAGE_LOAD_ADDRESS="0x40008000"
fi

if [ ! -z ${ARMSTRAP_UIMAGE_ENTRY_POINT} ]; then 
  BOARD_UIMAGE_ENTRY_POINT="${ARMSTRAP_UIMAGE_ENTRY_POINT}"
else
  BOARD_UIMAGE_ENTRY_POINT="0x40008000"
fi

BOARD_DPKG_LOCALPACKAGES="${ARMSTRAP_BOARDS}/.defaults/sunxi-dpkg/sunxi-tools_1.0-2_armhf.deb ${ARMSTRAP_BOARDS}/.defaults/sunxi-dpkg/update-uimage_1.0-1_armhf.deb ${BOARD_DPKG_LOCALPACKAGES}"
source ${ARMSTRAP_BOARDS}/.defaults/config.sh
