#! /usr/bin/env python3

import locale
import os
import sys
import subprocess

from lib import ui as UI
from lib import utils as Utils
from lib import disk as Disk
from lib import aos as aOS

locale.setlocale(locale.LC_ALL, '')

if __name__ == '__main__': 
    #Always work from where the script live!
    os.chdir(os.path.abspath(os.path.dirname(__file__)))

    config = Utils.readConfig("armStrap.ini")
    boards = Utils.readConfig(config['Board']['Branch'].lower() + ".ini")
    
    if UI.Summary(config) == "cancel":
        Utils.Exit(text = "armStrap will now exit", title = "Cancel by user", timeout = 5, status = os.EX_OK)
    
    status = UI.Status()
    
    if config.has_option('Output', 'Device'):
        (Device, partList) = Disk.formatSD(config = config, boards = boards, status = status)
    else:
        (Device, partList) = Disk.formatIMG(config = config, boards = boards, status = status)
        
    status.update_main(text = "", percent = 10)
        
    partMount = Disk.mountPartitions(Device = Device, partList = partList, status = status)
    

    status.update_main(text = "", percent = 15)
    
    aOS.installRootFS(url = "https://archive.armstrap.net/root", config = config, boards = boards, status = status)
    
    status.update_main(text = "", percent = 25)
    
    Disk.unmountPartitions(Device = Device, partList = partMount, status = status)
    
    status.end()
    status.join()
