BUILD_LC_ALL="" 
BUILD_LANGUAGE="en_US:en" 
BUILD_LANG="en_US.UTF-8"
  
BUILD_ARCH="arm"

case "${ARMSTRAP_OS}" in
  "ubuntu")  
     BUILD_ARMBIAN_ROOTFS="http://armstrap.vls.beaupre.biz/rootfs/ubuntu-13.04-armv7l-hf.txz"
     BUILD_ARMBIAN_SUITE="rarring"
     ;;
    *)
     BUILD_ARMBIAN_ROOTFS="http://armstrap.vls.beaupre.biz/rootfs/debian-wheezy-armv7l-hf.txz"
     BUILD_ARMBIAN_SUITE="wheezy"
     ;;
 esac
       
BUILD_ARMBIAN_EXTRACT="tar -xJ"
BUILD_ARMBIAN_KERNEL="http://armstrap.vls.beaupre.biz/kernel/cubieboard/install-cubieboard-linux-desktop-kernel-3.4.43+_3.4.43+-1_armhf.sh"
BUILD_ARMBIAN_UBOOT="http://armstrap.vls.beaupre.biz/uboot/cubieboard-u-boot.txz"
  
BUILD_MNT_ROOT="${ARMSTRAP_MNT}"
  
# Not all packages can be install this way.
BUILD_DPKG_EXTRAPACKAGES="nvi ntp ssh build-essential u-boot-tools parted git binfmt-support libusb-1.0-0 libusb-1.0-0-dev pkg-config dosfstools libncurses5-dev ${ARMSTRAP_DEBIAN_EXTRAPACKAGES}"
  
# Not all packages can be configured this way.
BUILD_UBUNTU_RECONFIG="tzdata ${ARMSTRAP_DPKG_RECONFIG}"
  
# Theses are packages included with or generated by the script. The script will automatically include .deb files in the dpkg directory
BUILD_DPKG_LOCALPACKAGES=""
  
BUILD_SERIALCON_ID="T0"
BUILD_SERIALCON_RUNLEVEL="2345"
BUILD_SERIALCON_TERM="ttyS0"
BUILD_SERIALCON_SPEED="115200"
BUILD_SERIALCON_TYPE="vt100"
 
BUILD_FSTAB_ROOTDEV="/dev/root"
BUILD_FSTAB_ROOTMNT="/"
BUILD_FSTAB_ROOTFST="ext4"
BUILD_FSTAB_ROOTOPT="defaults"
BUILD_FSTAB_ROOTDMP="0"
BUILD_FSTAB_ROOTPSS="1"
 
BUILD_KERNEL_MODULES="sw_ahci_platform lcd hdmi ump disp mali mali_drm"
  
BUILD_ROOT_DEV="/dev/mmcblk0p1"
BUILD_MAC_VENDOR=0x000246
  
BUILD_BOOT_CMD="${BUILD_MNT_ROOT}/boot/boot.cmd"
BUILD_BOOT_SCR="${BUILD_MNT_ROOT}/boot/boot.scr"
  
BUILD_CONFIG_CMDLINE="console=tty0 console=${BUILD_SERIALCON_TERM},${BUILD_SERIALCON_SPEED} hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x720p60 root=${BUILD_ROOT_DEV} rootwait panic=10"
  
BUILD_KERNEL_NAME="uImage"
 
BUILD_BOOT_FEX="${BUILD_MNT_ROOT}/boot/cubieboard.fex"
BUILD_BOOT_BIN="${BUILD_MNT_ROOT}/boot/script.bin"
BUILD_BOOT_BIN_LOAD="mmc 0 0x43000000 boot/script.bin"
BUILD_BOOT_KERNEL_LOAD="mmc 0 0x48000000 boot/${BUILD_KERNEL_NAME}"
BUILD_BOOT_KERNEL_ADDR="0x48000000"
 
#BUILD_BOOT_SPL="${BUILD_UBOOT_DIR}/spl/sunxi-spl.bin"
BUILD_BOOT_SPL_SIZE="1024"
BUILD_BOOT_SPL_SEEK="8"

#BUILD_BOOT_UBOOT="${BUILD_UBOOT_DIR}/u-boot.bin"
BUILD_BOOT_UBOOT_SIZE="1024"
BUILD_BOOT_UBOOT_SEEK="32"
  
BUILD_DISK_LAYOUT=("1:/:ext4:-1")

BUILD_SCRIPTS="init.sh build.sh"
BUILD_PREREQ="build-essential u-boot-tools qemu qemu-user-static debootstrap parted kpartx lvm2 git binfmt-support libusb-1.0-0-dev pkg-config dosfstools libncurses5-dev"
