BUILD_BOOTLOADER_NAME="a70xh"
BUILD_BOOTLOADER_FAMILY="Cubieboard2"
BUILD_BOOTLOADER_CPU="a20"
BUILD_BOOTLOADER_FEX="a70x.fex"

source ${ARMSTRAP_BOOTLOADERS}/${BUILD_BOOTLOADER_TYPE}/.defaults/config.sh
