BUILD_BOOTLOADER_FAMILY="Cubietruck"
BUILD_BOOTLOADER_CPU="a20"

BUILD_BOOTLOADER_FEXSRC="${ARMSTRAP_BOOTLOADERS}/${BUILD_BOOTLOADER_TYPE}/cubietruck"

source ${ARMSTRAP_BOOTLOADERS}/${BUILD_BOOTLOADER_TYPE}/.defaults/config.sh
